title: Texture Theme
author: SUNGJAE BAE
email: hsm0156@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  SUNGJAE BAE's portfolio
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: SUNGJAE BAE's portfolio
  tagline: Web Developer. Embedded Developer.
  date_format: "%Y %b %-d"
  style: green
  showNav: true
  showPicker: false
  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github: SUNGJAEBAE
    # linkedIn: in/thelehhman
    # rss: rss
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
